Cup 1372 charts
AppQuality/unguess-design-system pull request #94
Opened 2022-10-14 14:46 UTC by marcbon

- Pie Chart
- Bar Chart

2022-10-27 09:52 UTC, marcbon commented
Stream Chart
Default Color Scheme

2022-11-07 17:18 UTC, cannarocks requested changes

2022-11-07 17:18 UTC, cannarocks commented on src/index.tsx
> +
ci sono tutti?

2022-11-08 08:28 UTC, cannarocks requested changes

2022-11-08 08:28 UTC, cannarocks commented on src/stories/charts/bullet/index.tsx
> +      rangeColors={CHARTS_COLOR_SCHEME_MONO[1]}
Ma questi `CHARTS_COLOR_SCHEME_MONO` sparsi in giro? non mi sembra un modo leggibile di inserire colori

2022-11-08 08:28 UTC, cannarocks commented on src/stories/charts/bullet/index.tsx
> +      rangeComponent={rangeProps => (<CustomBulletChartRange fill={CHARTS_COLOR_SCHEME_MONO[1]} {...rangeProps} />)}
Anche qui, sarebbe molto più chiaro e leggibile inserire direttamente il colore grey[123] oppure esportare dai grafici una palette di colori più parlante.

2022-11-10 11:05 UTC, cannarocks approved these changes

2022-11-11 09:28 UTC, merged